name: Build MyRental Service

on:
    push:
        paths:
            - "rental-service/**"
            - ".github/workflows/rental-service.yml"
    pull_request:
        branches:
            - main
        paths:
            - "rental-service/**"
            - ".github/workflows/rental-service.yml"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Build MyRental Service Docker Image
            run: |
                    docker build --target production -t myrental-service:latest ./rental-service